name: Create HPI build 

on: 
  push:
    branches:
      - JenkinsPipeline

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out source
        uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
          architecture: x64
      - name: Build HPI
        run: mvn clean compile package hpi:hpi -Dmaven.javadoc.skip=true -DskipTests=true
      - name: Archive payload
        uses: actions/upload-artifact@master
        with:
          name: Compiled plugin
          path: target/kpp-management-plugin.*
